package Magicians;
import java.util.ArrayList;

//This is the GUI created from the Nimbus generator in Netbeans

public class GUI extends javax.swing.JFrame {

    private BookingList bookingList = new BookingList();
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameBox = new javax.swing.JTextField();
        BookingButton = new javax.swing.JButton();
        HolidayLabelBooking = new javax.swing.JLabel();
        HolidayComboBoxBooking = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookingTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        StatusHolidays = new javax.swing.JButton();
        HolidayLabelStatus = new javax.swing.JLabel();
        HolidayComboBoxStatus = new javax.swing.JComboBox();
        MagiciansLabel = new javax.swing.JLabel();
        MagiciansComboBox = new javax.swing.JComboBox();
        StatusMagicians = new javax.swing.JButton();
        WaitlistLabel = new javax.swing.JLabel();
        WaitlistComboBox = new javax.swing.JComboBox();
        WaitListStatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StatusTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        AddMagicianTextField = new javax.swing.JTextField();
        AddMagicianButton = new javax.swing.JButton();
        DropMagicianComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NameLabel.setText("Name: ");

        BookingButton.setText("Book");
        BookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingButtonActionPerformed(evt);
            }
        });

        HolidayLabelBooking.setText("Holiday: ");

        HolidayComboBoxBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HolidayComboBoxBookingActionPerformed(evt);
            }
        });

        BookingTextArea.setEditable(false);
        BookingTextArea.setColumns(20);
        BookingTextArea.setRows(5);
        jScrollPane2.setViewportView(BookingTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(NameLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(HolidayLabelBooking)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HolidayComboBoxBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(BookingButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HolidayLabelBooking)
                    .addComponent(HolidayComboBoxBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BookingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        ArrayList<String> holidays = bookingList.getHolidays();

        for(int x =0; x< holidays.size();x++)
        HolidayComboBoxBooking.addItem(holidays.get(x));

        jTabbedPane2.addTab("Book", jPanel1);

        StatusHolidays.setText("Status");
        StatusHolidays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PressButton(evt);
            }
        });

        HolidayLabelStatus.setText("Holiday: ");

        HolidayComboBoxStatus.setToolTipText("");

        MagiciansLabel.setText("Magicians:");

        StatusMagicians.setText("Status");
        StatusMagicians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusMagiciansPressButton(evt);
            }
        });

        WaitlistLabel.setText("Waitlist");

        WaitListStatus.setText("Status");
        WaitListStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaitListStatusPressButton(evt);
            }
        });

        StatusTextArea.setEditable(false);
        StatusTextArea.setColumns(20);
        StatusTextArea.setRows(5);
        jScrollPane1.setViewportView(StatusTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(HolidayLabelStatus)
                                .addGap(18, 18, 18)
                                .addComponent(HolidayComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MagiciansLabel)
                                    .addComponent(WaitlistLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MagiciansComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WaitlistComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StatusMagicians)
                            .addComponent(StatusHolidays)
                            .addComponent(WaitListStatus)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HolidayComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusHolidays)
                    .addComponent(HolidayLabelStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WaitListStatus)
                    .addComponent(WaitlistComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WaitlistLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StatusMagicians)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MagiciansLabel)
                        .addComponent(MagiciansComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        for(int x =0; x<holidays.size();x++)
        HolidayComboBoxStatus.addItem(holidays.get(x));
        ArrayList<String> magicians= bookingList.getMagicians();

        for(int x =0; x<magicians.size();x++)
        MagiciansComboBox.addItem(magicians.get(x));
        for(int x =0; x<holidays.size();x++)
        WaitlistComboBox.addItem(holidays.get(x));

        jTabbedPane2.addTab("Status", jPanel2);

        AddMagicianTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMagicianTextFieldActionPerformed(evt);
            }
        });

        AddMagicianButton.setText("Add Magician");
        AddMagicianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMagicianButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Drop Magician");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DropMagicianComboBox, 0, 145, Short.MAX_VALUE)
                            .addComponent(AddMagicianTextField))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddMagicianButton)
                            .addComponent(jButton1))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMagicianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddMagicianButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DropMagicianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        for(int x =0; x<magicians.size();x++)
        DropMagicianComboBox.addItem(magicians.get(x));

        jTabbedPane2.addTab("Add/Drop", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //booking button
    private void BookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingButtonActionPerformed
        String customerName = NameBox.getText();
        String holidayName = (String)HolidayComboBoxBooking.getSelectedItem();
        
        
        if(!NameBox.getText().isEmpty())
        {
            if(bookingList.addBooking(customerName, holidayName)==true)
                BookingTextArea.setText(bookingList.getHolidayBookingList(holidayName) + "\n\n" + bookingList.getWaitlist(holidayName));
            else
                BookingTextArea.setText(customerName+ " already has a booking for " + holidayName + ".");
        }
    }//GEN-LAST:event_BookingButtonActionPerformed
    
    //status holiday button
    private void PressButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PressButton
        String holidayName = (String)HolidayComboBoxStatus.getSelectedItem();
        StatusTextArea.setText(bookingList.getHolidayStatus(holidayName)+ "\n\n" + bookingList.getWaitlist(holidayName));
    }//GEN-LAST:event_PressButton

    //magician status button
    private void StatusMagiciansPressButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusMagiciansPressButton
        String magicianName = (String)MagiciansComboBox.getSelectedItem();
        StatusTextArea.setText(bookingList.getMagicianStatus(magicianName));
    }//GEN-LAST:event_StatusMagiciansPressButton

    //waitlist status button
    private void WaitListStatusPressButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaitListStatusPressButton
        String holidayName = (String)WaitlistComboBox.getSelectedItem();
        StatusTextArea.setText(bookingList.getWaitlist(holidayName));
    }//GEN-LAST:event_WaitListStatusPressButton

    private void HolidayComboBoxBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HolidayComboBoxBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HolidayComboBoxBookingActionPerformed

    private void AddMagicianTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMagicianTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMagicianTextFieldActionPerformed

    private void AddMagicianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMagicianButtonActionPerformed
        String newMagician = AddMagicianTextField.getText();
        bookingList.addMagician(newMagician);
        MagiciansComboBox.addItem(newMagician);
        DropMagicianComboBox.addItem(newMagician);
    }//GEN-LAST:event_AddMagicianButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String droppedMagician = (String)DropMagicianComboBox.getSelectedItem();
        bookingList.dropMagician(droppedMagician);
        MagiciansComboBox.removeItem(droppedMagician);
        DropMagicianComboBox.removeItem(droppedMagician);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMagicianButton;
    private javax.swing.JTextField AddMagicianTextField;
    private javax.swing.JButton BookingButton;
    private javax.swing.JTextArea BookingTextArea;
    private javax.swing.JComboBox DropMagicianComboBox;
    private javax.swing.JComboBox HolidayComboBoxBooking;
    private javax.swing.JComboBox HolidayComboBoxStatus;
    private javax.swing.JLabel HolidayLabelBooking;
    private javax.swing.JLabel HolidayLabelStatus;
    private javax.swing.JComboBox MagiciansComboBox;
    private javax.swing.JLabel MagiciansLabel;
    private javax.swing.JTextField NameBox;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JButton StatusHolidays;
    private javax.swing.JButton StatusMagicians;
    private javax.swing.JTextArea StatusTextArea;
    private javax.swing.JButton WaitListStatus;
    private javax.swing.JComboBox WaitlistComboBox;
    private javax.swing.JLabel WaitlistLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
